### PR TITLE
Rewrite NOT FOR MERGE

### PR DESCRIPTION
**Pull request by target-san**
Please review these changes and share your opinion.
It's not for merge because it lacks testing, and some features (like stack pool) must be brought back.
But you can observe general design, and more important, how coroutines would look like. And no FnBox :)

Oh yes, one more important detail. I reused Boost's approach with context stored on stack directly. That's because I consider `save` operation to be not only unsafe, but just dangerous. You can easily jump into state which is not consistent anymore.

### CODE REVIEW

**Comment by zonyitoo** [comment]
What if I just want to store the registers? For example, I create a new Coroutine and switch to it, then I will need to
1. Safe the current registers _onto the stack_
2. Restore the registers of that Coroutine
3. Do the jump.

The _stack_ in the 1st stack is actually the thread's stack, but if you store registers onto the stack directly, then I may have to allocate a new stack.

**Comment by target-san** [comment]
As I said, just storing current context isn't a very good idea IMO. I wrote an example in coroutine discussion thread. To be short, by storing current context you effectively allow jumping into it from the same thread. But the state you stored will almost certainly be invalid. And then it will kaboom.

And yes, the main idea is that you'll need separate stack for each coroutine. Because that stack is part of its state, and can't be treated as separate entity as long as coroutine lives. Though, you can create coroutine based on on-stack buffer. The downside is, you won't be able to jump out of it. And there will be no overflow protection. That's what I'm using in tests.

**Comment by zonyitoo** [comment]
Sounds reasonable, I should take deeper look in the code, I just read it on my phone.

**Comment by zonyitoo** [comment]
@target-san Ping. What's the status?

**Comment by target-san** [comment]
Sorry, didn't have spare time last month.
Further actions depend on your plans.
What's on coroutine-rs and coio-rs, and their integration with context-rs?

**Comment by zonyitoo** [comment]
Coroutine-rs and Coio-rs just use `Context::swap` in their code. But the problem is they can only run under x86_64 Linux and Windows, x86 Windows, but crash on the other platforms without reason.

I still don't know what happened in the assembly code, but since we are planning on writing new pieces of assembly code, I choose not to fix the current bug.

Also, I am keeping an eye on the `#[naked]` attribute, so that we can write inline asm instead of depending on gcc.

**Comment by target-san** [comment]
Okay, so I assume your main concern is support for other platforms.
As per #[naked], I've heard of proposal to support kind of LLVM assembler right in toolchain.

Regarding crashes you mentioned. Do they happen on some complex cases? Or simple single switch is enough?

**Comment by zonyitoo** [comment]
Debian x86, crashes every time.

**Comment by target-san** [comment]
Okay, I'm pulling back this one until I have some more to show.

**Pull request closed without merging**
