### PR TITLE
add save context function

### PR DESCRIPTION
**Pull request by Xudong-Huang**
also fix load context bug

### CODE REVIEW

**Comment by zonyitoo** [comment]
Why removed the `-> !` in `InitFn` and `Context::load`?

**Comment by Xudong-Huang** [comment]
the load function has the same effect as the swap function, it's not never return, just switch the context. if you need a function never return you can add an infinite loop at the end of the function. (e.g the init_fn).
in generator-rs library I use the load function to implement the yield primitive.

**Comment by zonyitoo** [comment]
@Xudong-Huang I insist that the `InitFn` should be a diverging function.

And about the `Context::load`, I think that should also be a diverging function, because if you wants to come back by context switch, you will never come back from the `Context::load` function.

Also for the `InitFn`, what would happen if your control runs out of the `InitFn`? Where should it return?

**Comment by zonyitoo** [comment]
As for your `generator-rs`, I also have a working example that implements asymmetric coroutines: https://github.com/zonyitoo/context-rs/blob/feature-diverging/examples/asymmetric.rs

This file is a part of [coroutine-rs](https://github.com/rustcc/coroutine-rs) project.

If you agree, I am going to revert the changes for binging back the `-> !` marks.

**Comment by Xudong-Huang** [comment]
I agree `InitFn` should be a diverging function. but `context::load` should not be. we can switch back to the save point where`context::save` was called. 

for the case in `InitFn`, you will always get to the saved point which is before the `context::load()`, so the load function would be called again and again if you switch to it again and again. to prevent the final return, we can add a infinite loop at the end of the function.

**Comment by zonyitoo** [comment]
But the `Context::load` will not return, right? You will call `Context::load` on the context that is saved by `Context::save`, when you load it, the control will switch to the point just after the `Context::save`, but not return from the `Context::load`.

The `Context::load` and `Context::save` pair is different from the `Context::swap`.

**Comment by Xudong-Huang** [comment]
Yes, you are right. Here the magic is you can still have some code do the type checking after the `load` function in compile time. if the `load` function is diverging, there will be a warning message.

**Comment by zonyitoo** [comment]
Ah.. I see your point... Ok.. I just restore the `InitFn`.

**Comment by dpc** [comment]
Now I don't get it. Where is this typechecking? :D

**Comment by zonyitoo** [comment]
If the `Context::load` is diverging, then if you write some codes after it, compiler will generate several warnings for unreachable codes.

**Comment by dpc** [comment]
Why would you be writing code after diverging function? :D

**Comment by zonyitoo** [comment]
You may use `Context::save` to save context before one `Context::load`, when you jump back, you may just jump over the `Context::load` and execute the rest part of code.

**Comment by dpc** [comment]
Like here: https://github.com/Xudong-Huang/context-rs/commit/cd3caac7e13dccb1e2280d3841d2de28456dee43#diff-e0934bb6f70a4f8c3baf22a773c14ec7R456
?

I would argue it's a rust compiler bug to complain about it if Context::load is executed conditionally.

**Comment by zonyitoo** [comment]
Hmm...

**Comment by dpc** [comment]
Look at the other case - someone putting some code after `Context::load` by mistake. Then the compiler will correctly warn about it. So the fact `Context::load` is diverging function is useful. And not marking it so because of the previous case, is (IMO) workarounding rustc wrong behaviour. Using `#[allow(...)]` would be a better workaround.

**Pull request merged**
