### PR TITLE
Add record_sp_limit and get_sp_limit for ARM

### LINKED ISSUE #24: record_sp_limit & get_sp_limit missing on ARM
For ARM, record_sp_limit and get_sp_limit don't use inline assembly but reference an extern "C" function that was once implemented as ASM in Rust.
Unfortunately that implementation was removed at some point, which leads to linker errors on ARM.

### PR DESCRIPTION
**Pull request by troplin**
fixes #24 
The code ist just copied from the Rust repo (latest version I could find).
It works for me but I don't understand it at all...

### CODE REVIEW

**Comment by zonyitoo** [comment]
Great! And would you mind to add these into the `1.0` branch? Because that would be the next release of `context-rs`, but it is still testing.

**Comment by zonyitoo** [comment]
Just for note, @lhecker you may need to pay attention on these commits.

**Comment by zonyitoo** [comment]
Ah, sorry. I was wrong. This doesn't need to be added in `1.0` branch.

**Comment by troplin** [comment]
That was just a quick fix to get mioco to work.
1.0 is very different from master, so I didn't even check that.

How far away is the 1.0 release? Currently I'm using patched versions from github of some projects but I'd prefer to use a pure crates.io based setup.

BTW, I've got it running on my NAS (WD EX4100, ARMv7 Hard Float) in a Docker Container based on Ubuntu.
If you want me to run some tests just drop me a note.

**Comment by lhecker** [comment]
Oh yeah @troplin! It would be extremely convenient and super nice if you could run some tests on ARM for us! I believe everything should work though… :sweat_smile:

For this you'd need to pull this repo and checkout the "1.0" branch. Could you then post the output of `cargo test` and `cargo bench` here please?

Also some shameless promotion of "our" other project: [coio](https://github.com/zonyitoo/coio-rs). :smile:

**Comment by troplin** [comment]
```
root@ecad3621123d:/context-rs# cargo test
[...]
running 5 tests
test context::tests::number_generator ... ok
test context::tests::resume_ontop ... ok
test stack::tests::stack_size_too_large ... ok
test context::tests::type_sizes ... ok
test stack::tests::stack_size_too_small ... FAILED

failures:

---- stack::tests::stack_size_too_small stdout ----
    thread 'stack::tests::stack_size_too_small' panicked at 'assertion failed: `(left == right)` (left: `32768`, right: `8192`)', src/stack.rs:216
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    stack::tests::stack_size_too_small

test result: FAILED. 4 passed; 1 failed; 0 ignored; 0 measured


root@ecad3621123d:/context-rs# cargo bench
[...]
running 5 tests
test context::tests::number_generator ... ignored
test context::tests::resume_ontop ... ignored
test context::tests::type_sizes ... ignored
test stack::tests::stack_size_too_large ... ignored
test stack::tests::stack_size_too_small ... ignored

test result: ok. 0 passed; 0 failed; 5 ignored; 0 measured

     Running target/release/context-71766f40368c7036

running 2 tests
test resume                ... bench:          46 ns/iter (+/- 0)
test resume_reference_perf ... bench:          12 ns/iter (+/- 1)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured

     Running target/release/stack-27509a8aef6e6b50

running 2 tests
test regular_alloc ... bench:         223 ns/iter (+/- 159)
test stack_alloc   ... bench:       2,476 ns/iter (+/- 764)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured
```

**Comment by lhecker** [comment]
Thanks @troplin! It's good to see that the Context methods work well. I (or @zonyitoo if has time before I'm awake) will take a look tomorrow (CET) and find out why this one test failed. Thanks for taking your time to test this. :blush:

**Comment by troplin** [comment]
> Also some shameless promotion of "our" other project: coio. :smile:

How is coio different (better) from mioco and or IOW why should I switch?
They seem quite similar, why the duplicate effort?

**Comment by troplin** [comment]
> I (or @zonyitoo if has time before I'm awake) will take a look tomorrow (CET) and find out why this one test failed.

No hurry, I got to get some sleep as well. We're in the same time zone.

**Comment by lhecker** [comment]
Hmm I took a quick glance at the stack allocation code and there does not seem to be an error except for a single one: When the page size is larger than the stack minimum size…

Could it be that this ARM system of yours has a page size of 32kB? I've never such large pages…

Regarding coio: It's in it's core a lot more complicated and advanced than mioco. While mioco is currently more stable and feature complete (afaik) it uses a very very simple scheduler for it's coroutines.
Coio on the other hand uses a more complex work stealing scheduler similar to the one used in Go and will ensure that threads never run out of work (I'm quite sure for instance that coio will show a lot lower latency variance). Due to this it's also a fair bit more complicated to develop though but in the coming 2-3 months some major changes will land in coio which will make it as feature rich and stable as mioco with the added bonus of having an advanced scheduler.

**Comment by zonyitoo** [comment]
@troplin Coroutines in Coio can be transferred to different worker threads. That would be the main difference between Coio and Mioco, which means that we uses completely different scheduling approach.

@lhecker I will look at this after I finished debugging the SIGSEGV on x86.

**Comment by troplin** [comment]
> Could it be that this ARM system of yours has a page size of 32kB? I've never such large pages…

Yes that's actually the case.

**Comment by lhecker** [comment]
Hey @troplin would you mind checking the latest commit in the 1.0 branch? It should fix the issue above.

**Comment by troplin** [comment]
```
running 6 tests
test context::tests::number_generator ... ok
test context::tests::resume_ontop ... ok
test context::tests::type_sizes ... ok
fatal runtime error: Could not unwind stack, error = 9
Process didn't exit successfully: `/context-rs/target/debug/context-30e53ad2e638d392` (signal: 4, SIGILL: illegal instruction)

To learn more, run the command again with --verbose.
```

Should I open an issue for this?
This could get lost here in the closed PR
EDIT: @lhecker

**Comment by zonyitoo** [comment]
@troplin @lhecker Please open a new issue for this.

**Pull request merged**
